export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILURE='LOGIN_FAILURE';
export const GET_USERS_DATA_SUCCESS='GET_USERS_DATA_SUCCESS';
export const GET_ADMINS_DATA_SUCCESS='GET_ADMINS_DATA_SUCCESS';




